swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /aportante/GenerarPlanillaActivos:
    post:
      tags:
      - aportante
      description: Recibe un periodo pago y devuelve un arreglo de json con la informaci贸n
        de la planilla
      operationId: PlanillasController.Generar planilla de activos
      parameters:
      - in: body
        name: body
        description: body for PeriodoPago
        required: true
        schema:
          $ref: '#/definitions/.PeriodoPago'
      responses:
        "200":
          description: '{string} string'
        "403":
          description: body is empty
  /incapacidades/:
    get:
      tags:
      - incapacidades
      description: obtiene todas las personas que pueden aplicar a cualquier n贸mina
      operationId: IncapacidadesController.GetPersonas
      parameters:
      - in: query
        name: documento
        description: documento de la persona
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.interface{}'
        "403":
          description: ""
  /incapacidades/incapacidadesPersona/{contrato}/{vigencia}:
    get:
      tags:
      - incapacidades
      description: obtiene todas las incapacidades activdas de una persona
      operationId: IncapacidadesController.IncapacidadesPorPersona
      parameters:
      - in: query
        name: documento
        description: documento de la persona
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.interface{}'
        "403":
          description: ""
  /pago/RegistrarPagos:
    post:
      tags:
      - pago
      description: Recibe los pagos para registrar seguridad social, les agrega un
        estado,
      operationId: PagoController.Registrar pagos de seguridad social
      parameters:
      - in: body
        name: body
        description: body for TrPeriodoPago
        required: true
        schema:
          $ref: '#/definitions/models.TrPeriodoPago'
      responses:
        "201":
          description: '{int} models.PeriodoPago'
        "403":
          description: body is empty
  /pagoSumarPagosSalud/{idPeriodoPago}:
    get:
      tags:
      - pago
      description: Suma el total de los pagos de salud y pensi贸n de ud
      operationId: PagoController.Sumar pagos de salid
      parameters:
      - in: id
        name: idPeriodoPago
        description: periodo
        schema:
          $ref: '#/definitions/.del'
  /periodo_pago/:
    get:
      tags:
      - periodo_pago
      description: get PeriodoPago
      operationId: PeriodoPagoController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.PeriodoPago'
        "404":
          description: not found resource
    post:
      tags:
      - periodo_pago
      description: create PeriodoPago
      operationId: PeriodoPagoController.Post
      parameters:
      - in: body
        name: body
        description: body for PeriodoPago content
        required: true
        schema:
          $ref: '#/definitions/models.PeriodoPago'
      responses:
        "201":
          description: '{int} models.PeriodoPago'
        "400":
          description: the request contains incorrect syntax
  /periodo_pago/{id}:
    get:
      tags:
      - periodo_pago
      description: get PeriodoPago by id
      operationId: PeriodoPagoController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.PeriodoPago'
        "404":
          description: not found resource
    put:
      tags:
      - periodo_pago
      description: update the PeriodoPago
      operationId: PeriodoPagoController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for PeriodoPago content
        required: true
        schema:
          $ref: '#/definitions/models.PeriodoPago'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.PeriodoPago'
        "400":
          description: the request contains incorrect syntax
    delete:
      tags:
      - periodo_pago
      description: delete the PeriodoPago
      operationId: PeriodoPagoController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
  /planillas/GenerarPlanillaActivos:
    post:
      tags:
      - aportante
      description: Recibe un periodo pago y devuelve un arreglo de json con la informaci贸n
        de la planilla
      operationId: PlanillasController.Generar planilla de activos
      parameters:
      - in: body
        name: body
        description: body for PeriodoPago
        required: true
        schema:
          $ref: '#/definitions/.PeriodoPago'
      responses:
        "200":
          description: '{string} string'
        "403":
          description: body is empty
  /utils/GetActualDate:
    get:
      tags:
      - utils
      description: obtiene la fecha actual del servidor
      operationId: UtilsController.GetActualTime
      parameters:
      - in: body
        name: body
        description: body for Beneficiarios content
        required: true
        schema:
          $ref: '#/definitions/.Beneficiarios'
      responses:
        "201":
          description: '{string} fecha_actual'
        "403":
          description: body is empty
definitions:
  .Beneficiarios:
    type: object
  .PeriodoPago:
    type: object
  .del:
    type: object
  .interface{}:
    type: object
  models.EstadoSeguridadSocial:
    title: EstadoSeguridadSocial
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.Pago:
    title: Pago
    type: object
    properties:
      DetalleLiquidacion:
        type: integer
        format: int64
      EntidadPago:
        type: integer
        format: int64
      Id:
        type: integer
        format: int64
      PeriodoPago:
        $ref: '#/definitions/models.PeriodoPago'
      TipoPago:
        type: integer
        format: int64
      Valor:
        type: number
        format: double
  models.PeriodoPago:
    title: PeriodoPago
    type: object
    properties:
      Anio:
        type: number
        format: double
      EstadoSeguridadSocial:
        $ref: '#/definitions/models.EstadoSeguridadSocial'
      Id:
        type: integer
        format: int64
      Liquidacion:
        type: integer
        format: int64
      Mes:
        type: number
        format: double
      TipoLiquidacion:
        type: string
  models.TrPeriodoPago:
    title: TrPeriodoPago
    type: object
    properties:
      Contratos:
        type: array
        items:
          type: string
      Pagos:
        type: array
        items:
          $ref: '#/definitions/models.Pago'
      PeriodoPago:
        $ref: '#/definitions/models.PeriodoPago'
tags:
- name: periodo_pago
  description: |
    PeriodoPagoController operations for PeriodoPago
- name: pago
  description: |
    PagoController operations for Pago
- name: planillas
  description: |
    PlanillasController operations for Planillas
- name: aportante
  description: |
    PlanillasController operations for Planillas
- name: incapacidades
  description: |
    IncapacidadesController operations for Incapacidades
- name: utils
  description: |
    UtilsController operations for Beneficiarios
