swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: jcamilosarmientor@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /aportante/GenerarPlanillaActivos/{limit}/{offset}:
    post:
      tags:
      - aportante
      description: Recibe un periodo pago y devuelve un arreglo de json con la información
        de la planilla
      operationId: PlanillasController.Generar planilla de activos
      parameters:
      - in: body
        name: body
        description: body for PeriodoPago
        required: true
        schema:
          $ref: '#/definitions/PeriodoPago'
      responses:
        "200":
          description: '{string} string'
        "403":
          description: body is empty
  /aportante/PruebaPlanilla/{limit}:
    get:
      tags:
      - aportante
      description: Recibe un periodo pago y devuelve un arreglo de json con la información
        de la planilla
      operationId: PlanillasController.Generar planilla de activos
      parameters:
      - in: body
        name: body
        description: body for PeriodoPago
        required: true
        schema:
          $ref: '#/definitions/PeriodoPago'
      responses:
        "200":
          description: '{string} string'
        "403":
          description: body is empty
  /conceptos_ibc/ActualizarConceptos/:
    post:
      tags:
      - conceptos_ibc
      description: Actualiza los hechos conceptos_ibc en el ruler
      operationId: ConceptosIbcController.ActualizarConceptos
      parameters:
      - in: body
        name: body
        description: body for ConceptosIbc content
        required: true
        schema:
          $ref: '#/definitions/models.ConceptosIbc'
      responses:
        "201":
          description: '{int} models.Alert'
        "404":
          description: body is empty
  /generador_reglas/ObtenerHechosCalculo:
    get:
      tags:
      - generador_reglas
      description: Obtiene los hechos de calculo para seguridad social
      operationId: GeneradorRelgasController.ObtenerHechosCalculo
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Alert'
        "404":
          description: error
  /generador_reglas/RegistrarNuevosHechos:
    post:
      tags:
      - generador_reglas
      description: Actualiza los nuevos conceptos y resoluciones de seguridad social
      operationId: GeneradorRelgasController.RegistrarNuevosHechos
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Alert'
        "404":
          description: error
  /incapacidades/BuscarPersonas/{documento}:
    get:
      tags:
      - incapacidades
      description: obtiene todas las personas que pueden aplicar a cualquier nómina
      operationId: IncapacidadesController.BuscarPersonas
      parameters:
      - in: query
        name: documento
        description: documento de la persona
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/interface{}'
        "403":
          description: ""
  /incapacidades/incapacidadesPersona/{contrato}/{vigencia}:
    get:
      tags:
      - incapacidades
      description: obtiene todas las incapacidades activdas de una persona
      operationId: IncapacidadesController.IncapacidadesPorPersona
      parameters:
      - in: query
        name: documento
        description: documento de la persona
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/interface{}'
        "403":
          description: ""
  /pago/CalcularSegSocial/{id}:
    get:
      tags:
      - pago
      description: Cálcula la seguridad social para una preliquidación correspondiente
      operationId: PagoController.CalcularSegSocial
      parameters:
      - in: id
        name: id
        description: preliquidación
        schema:
          $ref: '#/definitions/de'
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/*models.PagoSeguridadSocial'
  /pago/CalcularSegSocialHonorarios/{idPreliquidacion}:
    get:
      tags:
      - pago
      description: Cálcula la seguridad social para una preliquidación de honorarios
        o contratistas correspondiente
      operationId: PagoController.CalcularSegSocialHonorarios
      parameters:
      - in: id
        name: id
        description: preliquidación
        schema:
          $ref: '#/definitions/de'
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/*models.PagoSeguridadSocial'
  /pago/ConceptosIbc/:
    get:
      tags:
      - pago
      description: Obtiene todos los conceptos IBC del ruler y los cruza con los conceptos
        de nómina
      operationId: PagoController.ConceptosIbc
  /pago/GetInfoCabecera/{idPreliquidacion}:
    get:
      tags:
      - pago
      description: Obtiene información adicional para la cabecera
      operationId: PagoController.GetInfoCabecera
      parameters:
      - in: id
        name: idPeriodoPago
        description: periodo
        schema:
          $ref: '#/definitions/del'
  /pago/NovedadesPorPersona/{persona}:
    get:
      tags:
      - pago
      description: Obtiene todos los conceptos IBC del ruler y los cruza con los conceptos
        de nómina
      operationId: PagoController.NovedadesPorPersona
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/models.NovedadesPersonaSS'
  /pago/RegistrarPagos:
    post:
      tags:
      - pago
      description: Recibe los pagos para registrar seguridad social, les agrega un
        estado,
      operationId: PagoController.Registrar pagos de seguridad social
      parameters:
      - in: body
        name: body
        description: body for TrPeriodoPago
        required: true
        schema:
          $ref: '#/definitions/models.TrPeriodoPago'
      responses:
        "201":
          description: '{int} models.PeriodoPago'
        "403":
          description: body is empty
  /pago/SumarPagosSalud/{idPeriodoPago}:
    get:
      tags:
      - pago
      description: Suma el total de los pagos de salud y pensión de ud
      operationId: PagoController.Sumar pagos de salid
      parameters:
      - in: id
        name: idPeriodoPago
        description: periodo
        schema:
          $ref: '#/definitions/del'
  /planillas/GenerarPlanillaActivos/{limit}/{offset}:
    post:
      tags:
      - aportante
      description: Recibe un periodo pago y devuelve un arreglo de json con la información
        de la planilla
      operationId: PlanillasController.Generar planilla de activos
      parameters:
      - in: body
        name: body
        description: body for PeriodoPago
        required: true
        schema:
          $ref: '#/definitions/PeriodoPago'
      responses:
        "200":
          description: '{string} string'
        "403":
          description: body is empty
  /planillas/PruebaPlanilla/{limit}:
    get:
      tags:
      - aportante
      description: Recibe un periodo pago y devuelve un arreglo de json con la información
        de la planilla
      operationId: PlanillasController.Generar planilla de activos
      parameters:
      - in: body
        name: body
        description: body for PeriodoPago
        required: true
        schema:
          $ref: '#/definitions/PeriodoPago'
      responses:
        "200":
          description: '{string} string'
        "403":
          description: body is empty
  /utils/GetActualDate:
    get:
      tags:
      - utils
      description: obtiene la fecha actual del servidor
      operationId: UtilsController.GetActualDate
      parameters:
      - in: body
        name: body
        description: body for Beneficiarios content
        required: true
        schema:
          $ref: '#/definitions/models.Beneficiarios'
      responses:
        "201":
          description: '{string} fecha_actual'
        "403":
          description: body is empty
definitions:
  '*models.PagoSeguridadSocial':
    title: PagoSeguridadSocial
    type: object
  69.0xc000475b90.false:
    title: "false"
    type: object
  PeriodoPago:
    title: PeriodoPago
    type: object
  de:
    title: de
    type: object
  del:
    title: del
    type: object
  interface{}:
    title: interface{}
    type: object
  models.Alert:
    title: Alert
    type: object
    properties:
      Body:
        $ref: '#/definitions/69.0xc000475b90.false'
      Code:
        type: string
      Type:
        type: string
  models.Beneficiarios:
    title: Beneficiarios
    type: object
  models.ConceptoNomina:
    title: ConceptoNomina
    type: object
    properties:
      AliasConcepto:
        type: string
      Id:
        type: integer
        format: int64
      NaturalezaConcepto:
        $ref: '#/definitions/models.NaturalezaConceptoNomina'
      NombreConcepto:
        type: string
      TipoConcepto:
        $ref: '#/definitions/models.TipoConceptoNomina'
  models.ConceptoNominaPorPersona:
    title: ConceptoNominaPorPersona
    type: object
    properties:
      Activo:
        type: boolean
      Concepto:
        $ref: '#/definitions/models.ConceptoNomina'
      FechaDesde:
        type: string
        format: datetime
      FechaHasta:
        type: string
        format: datetime
      FechaRegistro:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
      Nomina:
        $ref: '#/definitions/models.Nomina'
      NumCuotas:
        type: integer
        format: int64
      Persona:
        type: integer
        format: int64
      ValorNovedad:
        type: number
        format: double
  models.ConceptosIbc:
    title: ConceptosIbc
    type: object
    properties:
      Descripcion:
        type: string
      DescripcionHecho:
        type: string
      Dominio:
        $ref: '#/definitions/models.Dominio'
      Estado:
        type: boolean
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      TipoPredicado:
        $ref: '#/definitions/models.TipoPredicado'
  models.DetallePreliquidacion:
    title: DetallePreliquidacion
    type: object
    properties:
      Concepto:
        $ref: '#/definitions/models.ConceptoNomina'
      DiasLiquidados:
        type: number
        format: double
      EstadoDisponibilidad:
        $ref: '#/definitions/models.EstadoDisponibilidad'
      Id:
        type: integer
        format: int64
      NumeroContrato:
        type: string
      Persona:
        type: integer
        format: int64
      Preliquidacion:
        $ref: '#/definitions/models.Preliquidacion'
      TipoPreliquidacion:
        $ref: '#/definitions/models.TipoPreliquidacion'
      ValorCalculado:
        type: number
        format: double
      VigenciaContrato:
        type: integer
        format: int64
  models.Dominio:
    title: Dominio
    type: object
    properties:
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
  models.EstadoDisponibilidad:
    title: EstadoDisponibilidad
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.EstadoPreliquidacion:
    title: EstadoPreliquidacion
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.EstadoSeguridadSocial:
    title: EstadoSeguridadSocial
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.NaturalezaConceptoNomina:
    title: NaturalezaConceptoNomina
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.Nomina:
    title: Nomina
    type: object
    properties:
      Activo:
        type: boolean
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      TipoNomina:
        $ref: '#/definitions/models.TipoNomina'
  models.NovedadesPersonaSS:
    title: NovedadesPersonaSS
    type: object
    properties:
      ConceptoNominaPorPersona:
        $ref: '#/definitions/models.ConceptoNominaPorPersona'
      Persona:
        type: integer
        format: int64
      Preliquidacion:
        $ref: '#/definitions/models.DetallePreliquidacion'
  models.Pago:
    title: Pago
    type: object
    properties:
      DetalleLiquidacion:
        type: integer
        format: int64
      EntidadPago:
        type: integer
        format: int64
      Id:
        type: integer
        format: int64
      PeriodoPago:
        $ref: '#/definitions/models.PeriodoPago'
      TipoPago:
        type: integer
        format: int64
      Valor:
        type: number
        format: double
  models.PeriodoPago:
    title: PeriodoPago
    type: object
    properties:
      Anio:
        type: number
        format: double
      EstadoSeguridadSocial:
        $ref: '#/definitions/models.EstadoSeguridadSocial'
      Id:
        type: integer
        format: int64
      Liquidacion:
        type: integer
        format: int64
      Mes:
        type: number
        format: double
      TipoLiquidacion:
        type: string
  models.Preliquidacion:
    title: Preliquidacion
    type: object
    properties:
      Ano:
        type: integer
        format: int64
      Descripcion:
        type: string
      EstadoPreliquidacion:
        $ref: '#/definitions/models.EstadoPreliquidacion'
      FechaRegistro:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
      Mes:
        type: integer
        format: int64
      Nomina:
        $ref: '#/definitions/models.Nomina'
  models.TipoConceptoNomina:
    title: TipoConceptoNomina
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.TipoNomina:
    title: TipoNomina
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.TipoPredicado:
    title: TipoPredicado
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
  models.TipoPreliquidacion:
    title: TipoPreliquidacion
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.TrPeriodoPago:
    title: TrPeriodoPago
    type: object
    properties:
      Pagos:
        type: array
        items:
          $ref: '#/definitions/models.Pago'
      PeriodoPago:
        $ref: '#/definitions/models.PeriodoPago'
      Personas:
        type: array
        items:
          type: string
tags:
- name: periodo_pago
  description: |
    PeriodoPagoController operations for PeriodoPago
- name: pago
  description: |
    PagoController operations for Pago
- name: planillas
  description: |
    PlanillasController operations for Planillas
- name: aportante
  description: |
    PlanillasController operations for Planillas
- name: incapacidades
  description: |
    IncapacidadesController operations for Incapacidades
- name: utils
  description: |
    UtilsController operations for Beneficiarios
- name: conceptos_ibc
  description: |
    ConceptosIbcController ...controlador de tipo beego.Controller
- name: pago_honorarios
  description: |
    PagoHonorariosController operations for Pago_honorarios
- name: generador_reglas
  description: |
    GeneradorRelgasController operations for Generador_relgas
