package models

// PlanillaTipoE Estructura para planilla de activos
type PlanillaTipoE struct {
	TipoRegistro                    string
	Secuencia                       int
	TipoDocumento                   string
	NumeroIdentificacion            string
	TipoCotizante                   int
	SubTipoCotizante                int
	ExtranjeroNoPension             string
	PrimerApellido                  string
	SegundoApellido                 string
	PrimerNombre                    string
	SegundoNombre                   string
	CodigoFondoPension              string
	TrasladoPension                 string
	CodigoEps                       string
	TrasladoEps                     string
	CodigoCCF                       string
	DiasLaborados                   int
	DiasPension                     int
	DiasSalud                       int
	DiasArl                         int
	DiasCaja                        int
	SalarioBase                     int
	SalarioIntegral                 string
	Ibcension                       int
	IbcSalud                        int
	IbcArl                          int
	IbcCcf                          int
	TarifaPension                   string
	PagoPension                     int
	AportePension                   int
	TotalPension                    int
	FondoSolidaridad                int
	FondoSubsistencia               int
	NoRetenidoAportesVolunarios     int
	TarifaSalud                     string
	PagoSalud                       int
	ValorUpc                        int
	AutorizacionEnfermedadGeneral   string
	ValorIncapacidadGeneral         int
	AutotizacionLicenciaMarternidad string
	ValorLicenciaMaternidad         int
	TarifaArl                       string
	CentroTrabajo                   string
	PagoArl                         int
	TarifaCaja                      string
	PagoCaja                        int
	TarifaSena                      string
	PagoSena                        int
	TarifaIcbf                      string
	PagoIcbf                        int
	TarifaEsap                      string
	PagoEsap                        int
	TarifaMen                       string
	PagoMen                         int
	TipoDocumentoCotizantePrincipal string
	DocumentoCotizantePrincipal     string
	ExoneradoPagoSalud              string
	CodigoArl                       string
	ClaseRiesgo                     string
	IndicadorTarifaEspecialPension  string
	FechasNovedades                 string
	IbcOtrosParaFiscales            int
	HorasLaboradas                  int
	EspacioBlanco                   string
}
